### PR TITLE
First try, maybe something is wrong.

### PR DESCRIPTION
**Pull request by kakurokan**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@kakurokan Hi there! Thanks for submitting. Looks like you're not creating the tables via code, so could you please commit the CREATE scripts?

**Comment by kakurokan** [comment]
Sorry, but how can I do that??

**Comment by TheCSharpAcademy** [comment]
> Sorry, but how can I do that??

In SQL server right click on the table > Script Table as > Create To > File, then commit that file in your project 

image

**Comment by kakurokan** [comment]
Like that?

**Comment by kakurokan** [comment]
Like that??

**Comment by kakurokan** [comment]
Eu also committed the stored procedures.

**Comment by TheCSharpAcademy** [comment]
> Eu also committed the stored procedures.

Sorry about the delay. Reviewing now 😆

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@kakurokan Apologies for the delay. Thanks for submitting the scripts. 😁

**There's one requirement missing:** 
image

I'm not letting it pass, because understanding Foreign Keys is important moving forward. Also, if you the tables are linked you can use the ON DELETE CASCADE property so that flashcards and study sessions are automatically deleted when stacks are deleted. I noticed you manually deleted them i nthe DeleteStack stored procedure.

**About stored procedures**, it comes down to personal preference, but I would avoid them for simple crud operations. If you need complex, expensive manipulation of data, maybe that's the case for a SP, but in general they're messy and impossible to debug. Not to mention the fact that all of the sudden you have business logic in SQL server, which adds to the mess. But all of this is my opinion, some devs are die-hard SP fans. 😆

**Comment by kakurokan** [comment]
Thank you for the feedback! You are right about the stored procedures, it can be a mess sometimes, this was my first try with them. I was using foreign keys, but I was not aware about the CASCADE property.

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@kakurokan hey there! I couldn't find the On Delete Cascade constraint. 🥺

image

**Comment by kakurokan** [comment]
Oh, I don't understand why. Look:
image
image

**Comment by kakurokan** [comment]
Maybe I did something wrong

**Pull request merged**
