### PR TITLE
first attempt at FlashCard project

### PR DESCRIPTION
**Pull request by heartingNinja**
My project is set up to choose a continent with a number. A flashcardDto list will be set up with flashcards that are part of that stackId. 10 random question will be sent to user one by one asking what is the capital of "country". User has to type the answer. Gets a correct or incorrect response. After 10 questions are answered new studysessions data is recorded in the StudySessionDto and the dbo.Study.Sessions. 

Users can delete a stack that would be a continent. When this happens the flashcards, stack, and studysessions with this Id are also deleted. The continent stacks reorder their numbers to always start at one and end with the last number after deleting.

### CODE REVIEW

**Comment by heartingNinja** [comment]
Saw that when a stack was deleted the sessionId while looking at records didn't change. The Id would skip numbers. Now that list will always start at 1 and increase by one after deleting a stack. Made a few changes to make more readable.

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@heartingNinja hi there! Just confirming... In your app the students aren't able to create/update stacks/flashcards? That would be ideal, and also good practice for you.

Also, I need you to send me the SQL scripts for the tables you created, otherwise I can't recreate your DB schema. I mean I could, but it would take me a lot of time. 😂 You can write them in your readme.

Let me know your thoughts.

**Comment by heartingNinja** [comment]
> @heartingNinja hi there! Just confirming... In your app the students aren't able to create/update stacks/flashcards? That would be ideal, and also good practice for you.
> 
> Also, I need you to send me the SQL scripts for the tables you created, otherwise I can't recreate your DB schema. I mean I could, but it would take me a lot of time. 😂 You can write them in your readme.
> 
> Let me know your thoughts.

I have added the create/update/ delete functions for the Flashcards and the Stacks. I also added a SQL folder that has AddData to explain how to use the 3 other text files to use the data I am using. Not sure how to share SQL files so just made them a text. Will also add on the Readme

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@heartingNinja sorry it took so long to grab this project for review. At the moment I'm getting this error when trying to create a new stack. Have a look into the "auto increment' key word for your table creation query. 

image

**Comment by TheCSharpAcademy** [comment]
@heartingNinja Let me know if you need help 😁

**Comment by TheCSharpAcademy** [comment]
@heartingNinja haven't heard from you in a while! 🥺

**Comment by TheCSharpAcademy** [comment]
@heartingNinja  feel free to reopen if you want to proceed 😊

**Pull request closed without merging**
