### PR TITLE
Finished project

### PR DESCRIPTION
**Pull request by David-Nakeeran**

### CODE REVIEW

**Review by chrisjamiecarter — CHANGES_REQUESTED** [review]
Hey @David-Nakeeran 👋 ,

🔴 **Submodule**
Looks like your submission contained a .git folder inside your project's. That means it was picked up as a submodule. You can see the files your PR contains here in the "Files Changed" tab.

image

You have to exclude it, then commit again. If it doesn't work just create a new PR, this time moving your project into our repo without the git folder. Bear in mind this folder sometimes is hidden.

Feel free to reach out if you have any questions 🆘 .

I will go ahead and wait for you to make your changes, commit and push (which will then notify me) 😊 !

Thanks,
@chrisjamiecarter 👍

**Comment by David-Nakeeran** [comment]
I have removed the .gitignore and have pushed, hopefully everything will be ok this time.

**Comment by chrisjamiecarter** [comment]
@David-Nakeeran Not the `.gitignore` file... the `.git` folder.

You may need to check `Hidden items`.

Then delete `.git` folder in YOUR project folder. I imagine this may be called `Flashcards.David-Nakeeran` or similar.

Be careful, as there will be a `.git` folder in the root `CodeReviews.Console.Flashcards` folder - this should remain.

I have obfuscated the below to not confuse things, but added some orange circles to show my instructions.

image

If you get stuck reach out in Discord.

Thanks
@chrisjamiecarter

**Comment by David-Nakeeran** [comment]
Hi Chris,

So I had to make a new PR(git folder deleted now), but I can't submit the
project again.

David

**Comment by chrisjamiecarter** [comment]
👍 No worries @David-Nakeeran I got the new one

**Comment by David-Nakeeran** [comment]
That’s great! Thank you for your help 🙂

David

**Pull request closed without merging**
