### PR TITLE
Complete.

### PR DESCRIPTION
**Pull request by Speedierone**

### CODE REVIEW

**Comment by Speedierone** [comment]
Remaining errors are for Using System.Config.

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Speedierone Looks like you're close! Well done on submitting this complex project. This is what I need from you. 
1 - If you're not creating your tables in code, I need the SQL scripts so I can create them myself.
2 - Line 104 is very misleading. Basically you're saying any database error caught by the DB will prompt the same message, which is almost never true. It's not good practice to deal with expected errors using exceptions. Exceptions are for errors you don't expect. It's better to do another DB call to check if the subject exists beforehand and deal with the error with an if block.

**Comment by Speedierone** [comment]
@TheCSharpAcademy I have 3 tables which i will send as 3 separate messages so they dont get confusing. Ive just right clicked and done script table as and then create to so i am hoping this is the correct way to do it. They database name is FlashCards.

**Comment by Speedierone** [comment]
USE [FlashCards]
GO

/****** Object:  Table [dbo].[Questions]    Script Date: 15/05/2023 16:27:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Questions](
	[ID] [int] NOT NULL,
	[FlashSubject] [nvarchar](50) NOT NULL,
	[FrontOfCard] [nvarchar](50) NULL,
	[BackOfCard] [nvarchar](50) NULL,
 CONSTRAINT [PK_Questions] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [CustomIDUnique] UNIQUE NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Questions] ADD  CONSTRAINT [DF_Questions_ID]  DEFAULT ((1)) FOR [ID]
GO

ALTER TABLE [dbo].[Questions]  WITH CHECK ADD  CONSTRAINT [FK_FlashCards_Stack] FOREIGN KEY([FlashSubject])
REFERENCES [dbo].[Stack] ([Subject])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Questions] CHECK CONSTRAINT [FK_FlashCards_Stack]
GO

**Comment by Speedierone** [comment]
USE [FlashCards]
GO

/****** Object:  Table [dbo].[Stack]    Script Date: 15/05/2023 16:26:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Stack](
	[Subject] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Stack] PRIMARY KEY CLUSTERED 
(
	[Subject] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

**Comment by Speedierone** [comment]
USE [FlashCards]
GO

/****** Object:  Table [dbo].[StudyGames]    Script Date: 15/05/2023 16:24:52 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[StudyGames](
	[Date] [date] NOT NULL,
	[Subject] [nvarchar](50) NOT NULL,
	[GameScore] [float] NOT NULL,
	[GameAmount] [int] NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[StudyGames]  WITH CHECK ADD  CONSTRAINT [FK_StudyGames_Stack] FOREIGN KEY([Subject])
REFERENCES [dbo].[Stack] ([Subject])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[StudyGames] CHECK CONSTRAINT [FK_StudyGames_Stack]
GO

**Comment by Speedierone** [comment]
There is also a trigger that I have setup on the dbo.Questions table so will add that as well.

USE [FlashCards]
GO

/****** Object:  Trigger [dbo].[ID_reorder]    Script Date: 15/05/2023 16:33:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[ID_reorder]
ON [dbo].[Questions]
AFTER DELETE
AS
BEGIN
    SET NOCOUNT ON;
    UPDATE Questions
    SET ID = (SELECT COUNT(*) FROM Questions WHERE ID < deleted.ID) + 1
    FROM Questions
    JOIN deleted ON Questions.ID >= deleted.ID;
END;

GO

ALTER TABLE [dbo].[Questions] ENABLE TRIGGER [ID_reorder]
GO

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Speedierone Sorry it took so long to grab this project for review.

I've created the tables as per your scripts but I'm getting this error when trying to create a stack: 

image

I believe it's because the nvarchar size defaults to 1 if you don't specify the size. 

image


Could you please check your scripts?

**Comment by TheCSharpAcademy** [comment]
@Speedierone Haven't heard from you in a while! 😁

**Comment by TheCSharpAcademy** [comment]
@Speedierone Closing this as it's been more than a month, but feel free to reopen if you want to proceed 😊

**Pull request closed without merging**
