### PR TITLE
Project ready for review

### PR DESCRIPTION
**Pull request by SCM42**

### CODE REVIEW

**Comment by Jinboi** [comment]
Hi @SCM42 , 

Thank you very much for submitting your project and your patience. 

While your project looks great, I've found a minor issue that needs to be fixed. 

1. Unique Flashcards

image

It looks like flashcards could be duplicated. I was able to create multiple flashcards with cardFront of 'test1' but with different answers.

____________________________________________

Below is just two cents from me—please ignore if irrelevant.

2. Calling Font

Also just a heads up that I couldn't run your project as-is and that I need to re-route the fontPath. It could be my own computer issue though. 

image

3. Refactoring /  Regions 

Again, this is just another two cents from me—but consider refactoring controller.cs. Maybe it was a design choice, but me personally, I thought it was too lengthy. Maybe you could use regions like below if you don't want to refactor. 

image

Hope you find this helpful and please let me know if there's anything I can help you with. Happy Coding! 

Cheers! 
-Youngwoo

**Comment by Jinboi** [comment]
Please ping me using @Jinboi when you re-submit and ready be reviewed again. Thank you! :D

**Comment by SCM42** [comment]
Will do thank you!

**Comment by SCM42** [comment]
Hi, @Jinboi ! I implemented your suggestions.

- I had added the UNIQUE constraint to the Stack Name when I first made the tables in SSMS but, completely forgot to implement them when writing the methods for creating them in my code. Both the Stack Name and Flashcard Front have the UNIQUE constraint now.

- I encountered the same issue in my last project with loading the figlet font. I fixed it by adding it to the build in the csproj.file. I did the same here so hopefully that fixes it.

- It would probably take me a while to refactor the controller so I did add the regions to it like you suggested. I agree that the class is a bit too long. I had considered making more controller files, one for handling stacks, one for handling flashcards. I did this with the study sessions because the tips for the project said to treat it like another application. Would it have been bad practice to make more of these controllers in the scope of MVC?

This is ready to be reviewed again and hopefully I have adequately fixed everything.

Thank you!

**Comment by Jinboi** [comment]
Hi @SCM42 ,

Thank you for re-submitting your project!

I'll mark this as completed. Please move on to the next project!

As for your question, like you have considered, I think you should have multiple controllers such as 

FlashcardController.cs
StackController.cs
StudySessionController.cs

and so on.

And to be honest, I'm fairly new to this coding/programming so I can't give you much advice. 
But if you have time, please take a look at this: https://github.com/chrisjamiecarter/flashcards/tree/main 

Chris is a senior software engineer who recently joined TCSA to expand his portfolio and this is low-key what I refer to as an answer sheet. 

Hope you find this helpful!

Thank you and Happy Coding!

Cheers,
-Youngwoo

**Pull request closed without merging**
