### PR TITLE
Finished Flashcards app

### PR DESCRIPTION
**Pull request by JvR-Hannes**

### CODE REVIEW

**Comment by Jinboi** [comment]
Hi @JvR-Hannes ,

Thank you for submitting your project!

While your project looks great, it seems like there's functinoality for stacks but not for flashcards.

I can create, read, update and delete stacks, but I cannot add flashcards within the stacks. 

Also, this requirement is not fulfilled:

"When showing a stack to the user, the flashcard Ids should always start with 1 without gaps between them. If you have 10 cards and number 5 is deleted, the table should show Ids from 1 to 9."

image

Can you please look into this when you have time? Thank you!

Happy Coding! 

Cheers,
-Youngwoo

**Comment by TheCSharpAcademy** [comment]
@JvR-Hannes Let us know if you need help 🤓

**Comment by JvR-Hannes** [comment]
Hi @Youngwoo

I am going to be honest with you. This 1 rattled me. I'm not really sure
where to start looking for the issue. Did I link the stacks wrong?
Did I link the flashcards?
I will have a look, I stayed on the basic requirements just to see if I am
doing it correctly. I will complete challenges when I feel comfortable with
the main requirements and that I understand it completely.

Thank you

**Comment by Jinboi** [comment]
image

"When showing a stack to the user, the flashcard Ids should always start with 1 without gaps between them. If you have 10 cards and number 5 is deleted, the table should show Ids from 1 to 9."

As far as I understand, this is a main requirement for the project that the list should start with 1. 

I understand that it could be frustrating sometimes. 

Have you tried to reach out to our discord community? I'm sure a lot of people are there to help you.

https://discord.gg/aDMDET8ywB

**Comment by TheCSharpAcademy** [comment]
@JvR-Hannes  It's been two weeks since the suggested changes, so we're archiving this project. Feel free to reopen the PR and resubmit in the academy when you're ready. 🤓@Jinboi You'll get the points regardless.

**Pull request closed without merging**
