### PR TITLE
Flash Cards Project Submission

### PR DESCRIPTION
**Pull request by thomas-henley**

### CODE REVIEW

**Comment by Jinboi** [comment]
Hi @thomas-henley ,

Thank you for your patience and thank you for submitting your project.

Your project looks great but I couldn't run your program.

When I tried to launch, I get this error message.

image

Could you please look into this? 

I"m sure I can mark this project as completed shortly if you can advise on this. Thank you!

Cheers,
-Youngwoo

**Comment by Jinboi** [comment]
Please ping me using @Jinboi when you're ready. Thank you!

**Comment by thomas-henley** [comment]
Hi @Jinboi ,

Thanks for taking a look! I can't reproduce the issue on my end, and I don't see a lot of room for there to be a problem. The "Stacks" table gets dropped here:
```
        if (_config["UseExampleData"] is "True")
        {
            DropTable("Cards");
            DropTable("StudySessions");
            DropTable("Stacks");
            CreateStacksTable();
            CreateCardsTable();
            CreateStudySessionsTable();
            PopulateDatabase();
        }
 ```
 "Cards" and "StudySessions" are the only other tables I make and they both get dropped first if they exist.
 
 It's a bit of a stretch, but is it possible the conflict is coming from tables left over from you reviewing other projects? If anyone else is using the database name "FlashCardsDB" they might be leaving tables behind in your LocalDB that also have foreign key references to "Stacks".

**Comment by Jinboi** [comment]
Hot damn—you must have some hawk eyes, sir! I do have a database called FlashCardsDB in my server. 
Thanks for your advice! I'll try again.

**Comment by Jinboi** [comment]
Hi @thomas-henley ,

I was able to review your project thanks to your advice!

Your project looks amazing! I'll mark it as completed. Please move on to the next project!

Thank you and Happy Coding!

Cheers,
-Youngwoo

**Pull request closed without merging**
