### PR TITLE
Done with the Flashcard project.

### PR DESCRIPTION
**Pull request by kalsson**

### CODE REVIEW

**Review by Doc415 — CHANGES_REQUESTED** [review]
Hey it was all going well until this one :)
when i try to delete a flash card, it asks me for stack, if i enter a invalid stack name
it warns me that there is no stack with that name and still asks for card id to delete
image
if i enter a number it deletes a flash card from db , that i didnt choose. if i enter a id that does not exists it throws exception

**Comment by kalsson** [comment]
Thanks for the feedback, I will fix it later. I can't understand that I didn't notice that myself 🤣

**Comment by Doc415** [comment]
> Thanks for the feedback, I will fix it later. I can't understand that I didn't notice that myself 🤣

and also

if i enter a string to  instead of id to delete stack , it throws exception.
image

**Comment by kalsson** [comment]
Hey mate,

Can you please check it again? 😁

**Comment by kalsson** [comment]
@Doc415

**Comment by Doc415** [comment]
> Hey mate,
> 
> Can you please check it again? 😁
> 
> @Doc415

First issue seems to be fixed , yet the second issue is still there
image



https://github.com/TheCSharpAcademy/CodeReviews.Console.Flashcards/assets/94632226/6baad8e1-ab90-4206-a048-23b65635d2d2

still needs a validation for type

**Review by Doc415 — CHANGES_REQUESTED** [review]
needs validation for type when deleting stack
:)

**Comment by kalsson** [comment]
> > Hey mate,
> > Can you please check it again? 😁
> > @Doc415
> 
> First issue seems to be fixed , yet the second issue is still there image
> 
>  Isimsiz.video.Clipchamp.ile.yapildi.16.mp4 
> still needs a validation for type mate :)

Thanks for the awesome feedback mate, I like when you use a video to show what you mean. I have fixed the validation now. 😁

**Review by Doc415 — APPROVED** [review]
Nice work mate :) looking forward to see your full-stack projects.

**Comment by kalsson** [comment]
> Nice work mate :) looking forward to see your full-stack projects.

Thanks buddy and thank you for the feedback. I'm looking forward to the other projects, I'm not a big fan of Console but it is very powerful.

**Pull request closed without merging**
