### PR TITLE
Completed project

### PR DESCRIPTION
**Pull request by eddyfadeev**
Hi,

Please review the project and let me know if there are any issues.
Thank you!

### CODE REVIEW

**Comment by eddyfadeev** [comment]
Interestingly that checks are showing false issues

**Comment by Jinboi** [comment]
Hi @eddyfadeev ,

Thank you for submitting your project and thank you for your patience.

While your project looks great, I ran into some problem when trying to launch your project.

Below is your original appsettings.json:

image

Below is my MSSQL: 

image

So I've updated the appsettings.json to run the program but I run into this error as below

image

Can please advise as to how I can launch your project if it's possible? 

Please and thank you!

Cheers,
-Youngwoo

**Comment by eddyfadeev** [comment]
Hi @Jinboi ,

I made adjustments to my code. The issue was that I had a database created already. With the latest changes, the database is specified in the appsettings file, and the code, and ConnectionProvider ensures that there is a database with such a name. 

Just pull the updated code and try to start it.

Thank you! 

Have a great day!
Eduard

**Comment by Jinboi** [comment]
Hi @eddyfadeev ,

Thank you for your re-uploading your project. 

I was able to launch and review your project, thanks to your help!

Your project looks great!! It's amazing that you could download your study history as a pdf file. 

This is just my two cents below—please ignore if irrelevant. 

Maybe it's because I'm too noob to understand but I felt that your project was very convoluted and complicated with too many folders. 

Have you considered having a library project within your application, like how we had Calculator and CalculatorLibrary in Console Project #2: Calculator Project? 

I think if you could do separation of concerns on the project-level, not only on the folder-level, it wouldn't feel as convoluted. 

But again, this was just my two cents. I'm sure you know more and  maybe it was your design choice hahaha

I'll mark your project as completed and please move on to the next project! 

Thank you and Happy Coding!

P.S Canucks > Oilers, Eh? Hahahahaha

Cheers,
-Youngwoo

**Comment by eddyfadeev** [comment]
Hey @Jinboi,

Thank you for the review!

Well, it does make sense, thanks for the suggestion. I will definitely try that out, but after finishing the Phone Book project, since the fact that it is almost done.

Have a great day!

Regards,
Eduard

P.S. Naaah, Let's Go Oilers! 😁

**Pull request closed without merging**
