### PR TITLE
finished project

### PR DESCRIPTION
**Pull request by Bina28**
Hi, could you please check my code? I'm looking for feedback or any issues you might spot. Thanks!))

### CODE REVIEW

**Review by chrisjamiecarter — CHANGES_REQUESTED** [review]
Hey @Bina28 👋,

Well done for submitting your project.

From your PR comment:
> Hi, could you please check my code? I'm looking for feedback or any issues you might spot. Thanks!))

Did you actually run and test your code yourself?

I am getting the following error:

image

Also note, there is no readme file in your project, so I had to guess that I needed to create the database myself... not a great start!

Please fix the error, **fully test your application yourself**, and then commit and push your changes to update this PR.

Make sure you test against a clean/fresh database (i.e., a freshly created database, no tables, no data).

Thanks
@chrisjamiecarter 👍

**Comment by TheCSharpAcademy** [comment]
@Bina28 Let us know if you need help! 🤓

**Comment by Bina28** [comment]
Hi, thanks! I think I've finally found a solution. I will test the application one more time and if everything is fine I will sent it today for revision))

________________________________
Fra: The C# Academy ***@***.***>
Sendt: mandag, desember 16, 2024 10:21:36 p.m.
Til: TheCSharpAcademy/CodeReviews.Console.Flashcards ***@***.***>
Kopi: Albina Diakova ***@***.***>; Mention ***@***.***>
Emne: Re: [TheCSharpAcademy/CodeReviews.Console.Flashcards] finished project (PR #121)


@Bina28<https://github.com/Bina28> Let us know if you need help! 🤓

**Review by chrisjamiecarter — APPROVED** [review]
Hey @Bina28 👋 ,

Great job on getting your updates pushed through 💪 .

You now fulfill all the requirements 🥇 !

***

I will go ahead and mark as approved, keep up the excellent work on the next projects! 😊

Best regards,
@chrisjamiecarter 👍

**Pull request closed without merging**
