### PR TITLE
Speedierone Complete

### PR DESCRIPTION
**Pull request by Speedierone**

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@Speedierone Good to have you back! 😎

I realise you're not creating the tables via code. In that case, could you please submit the scripts for me to create it? Thanks!

**Comment by Speedierone** [comment]
going to see if i can work out creating the tables as part of the code :)

**Comment by Speedierone** [comment]
Decided that I will try this on the next project i do so for now i will give you the code used in SQL server manager to create the databases.

**Comment by Speedierone** [comment]
Question table
USE [FlashCards]
GO

/****** Object:  Table [dbo].[Questions]    Script Date: 13/11/2023 19:10:40 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Questions](
	[ID] [int] NOT NULL,
	[FlashSubject] [nvarchar](50) NOT NULL,
	[FrontOfCard] [nvarchar](50) NULL,
	[BackOfCard] [nvarchar](50) NULL,
 CONSTRAINT [PK_Questions] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [CustomIDUnique] UNIQUE NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Questions] ADD  CONSTRAINT [DF_Questions_ID]  DEFAULT ((1)) FOR [ID]
GO

ALTER TABLE [dbo].[Questions]  WITH CHECK ADD  CONSTRAINT [FK_FlashCards_Stack] FOREIGN KEY([FlashSubject])
REFERENCES [dbo].[Stack] ([Subject])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Questions] CHECK CONSTRAINT [FK_FlashCards_Stack]
GO

**Comment by Speedierone** [comment]
stack table

USE [FlashCards]
GO

/****** Object:  Table [dbo].[Stack]    Script Date: 13/11/2023 19:12:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Stack](
	[Subject] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Stack] PRIMARY KEY CLUSTERED 
(
	[Subject] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

**Comment by Speedierone** [comment]
study game table.

USE [FlashCards]
GO

/****** Object:  Table [dbo].[StudyGames]    Script Date: 13/11/2023 19:12:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[StudyGames](
	[Date] [date] NOT NULL,
	[Subject] [nvarchar](50) NOT NULL,
	[GameScore] [float] NOT NULL,
	[GameAmount] [int] NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[StudyGames]  WITH CHECK ADD  CONSTRAINT [FK_StudyGames_Stack] FOREIGN KEY([Subject])
REFERENCES [dbo].[Stack] ([Subject])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[StudyGames] CHECK CONSTRAINT [FK_StudyGames_Stack]
GO

**Comment by TheCSharpAcademy** [comment]
@Speedierone Well done! I'm approving the project as you're demonstrating the expected skills. 😎 I just have a couple of observations

1 - In the scripts you provided the nvarchar columns don't specify the number of characters. Then they default to 1, so I could only insert one character in those column:

image

2 - The code for pivoting the table is sound, however it would be good to group by year/date, or the sessions will be recorded per month regardless of the year. This is a common scenario in web dev, so I recommend you modify the code to practice that skill.

Other than that, well done! 🥸

**Pull request merged**
