### PR TITLE
finished the flashCard requirement and challenges

### PR DESCRIPTION
**Pull request by ukpagrace**

### CODE REVIEW

**Comment by Jinboi** [comment]
Hi @ukpagrace ,

Thank you for submitting your project!

Sorry—this might be a dumb question but I keep running into this error when trying to run your program. 

image

I tried to change the AppSettings to my local server such as 

<appSettings>
    <add key="ConfigurationString" value="Data Source=(LocalDB)\\LocalDBDemo;Initial Catalog=FlashcardTracker;Integrated Security=True;Trust Server Certificate=True" />
</appSettings>

And created a database 'FlashcardTracker' within the server to see if it would work but that still wouldn't work. 

I lack the experience to say this with confidence but could you perhaps add your database as well or add codes to check if your database exists and create a database if there isn't a database? Thank you!

**Comment by ukpagrace** [comment]
> Hi @ukpagrace ,
> 
> Thank you for submitting your project!
> 
> Sorry—this might be a dumb question but I keep running into this error when trying to run your program.
> 
> image
> 
> I tried to change the AppSettings to my local server such as
> 
> And created a database 'FlashcardTracker' within the server to see if it would work but that still wouldn't work.
> 
> I lack the experience to say this with confidence but could you perhaps add your database as well or add codes to check if your database exists and create a database if there isn't a database? Thank you!

Hey @Jinboi  This is occurring because part of the connection string is my computer Name, that's the servers name. Since it's local connection.

**Comment by ukpagrace** [comment]
Hi @ukpagrace ,

Thank you for submitting your project!

Sorry—this might be a dumb question but I keep running into this error when trying to run your program.

image

I tried to change the AppSettings to my local server such as

And created a database 'FlashcardTracker' within the server to see if it would work but that still wouldn't work.

I lack the experience to say this with confidence but could you perhaps add your database as well or add codes to check if your database exists and create a database if there isn't a database? Thank you!

Hey @Jinboi This is occurring because part of the connection string is my computer Name, that's the servers name. Since it's local connection.

**Comment by Jinboi** [comment]
Hi @ukpagrace ,

Yes—thank you for your advice and I was able to run your program.

Your project looks great! 😄 

I'll mark it completed and please move on to the next project! Thank you!

**Comment by stevietv** [comment]
This one wasn't taken or approved in academy dashboard, I have approved it there.

**Pull request closed without merging**
