### PR TITLE
Gautatyr finished project

### PR DESCRIPTION
**Pull request by Gautatyr**
Here is my latest project.

I ended up dropping one requirement in the end, and let the database id for the flashcards.
The reason is that while I searched how to "Reset" the ids in the database, I found that most people advised against it.
So I thought about using a "sequence id" instead in the display, keeping the database id hidden from the user, and using a sequence id in the display table instead.

Now I don't know if I missed it in the documentation, but I didn't find a way to hide a column using ConsoleTableExt, and I didn't want to build the table by hand since it would have presented badly.

My last idea was to create a flashcard DTO with a sequence id and no database id, but it would've disrupted the way I fetch the flashcard in other parts of the application.

Considering the time it would've taken me, and what it brings, I decided to finish the application without this feature.
I hope it can still be considered done.

Anyways thank you again for your work !
Have a great day.

### CODE REVIEW

**Comment by TheCSharpAcademy** [comment]
@Gautatyr Looks like there was something wrong with the commit, the project itself wasn't checked in 😨

**Comment by TheCSharpAcademy** [comment]
> Here is my latest project.
> 
> I ended up dropping one requirement in the end, and let the database id for the flashcards. The reason is that while I searched how to "Reset" the ids in the database, I found that most people advised against it. So I thought about using a "sequence id" instead in the display, keeping the database id hidden from the user, and using a sequence id in the display table instead.
> 
> Now I don't know if I missed it in the documentation, but I didn't find a way to hide a column using ConsoleTableExt, and I didn't want to build the table by hand since it would have presented badly.
> 
> My last idea was to create a flashcard DTO with a sequence id and no database id, but it would've disrupted the way I fetch the flashcard in other parts of the application.
> 
> Considering the time it would've taken me, and what it brings, I decided to finish the application without this feature. I hope it can still be considered done.
> 
> Anyways thank you again for your work ! Have a great day.

I might approve it regardless since I don't want to be overly strict. But I'm wondering why the creation of a DTO would disrupt fetching data elsewhere. You could simply map the data to the view and from the user input. The DTO would be at the end of the chain, not interfering with how you fetch data. An example can be seen here: 

image

In this code I have class that's responsible for printing the data to the user. When I'm about to pass the data into ConsoleTableExt I map it creating a new Id in a FlashCardToView (which is the DTO). When the user picks an Id, I have to map back. It's not absolutely trivial but shouldn't be hard either. 😊

**Comment by Gautatyr** [comment]
Thank you for the review !
I followed your suggestion and modified the app, it now displays ids properly.

**Comment by TheCSharpAcademy** [comment]
@Gautatyr I think you've done a "git init" inside your project, which means that it became a submodule of the main git repo. That way I can't see any of the checked in files 😔

image

**Comment by Gautatyr** [comment]
Hey sorry about that, it should be resolved with this commit

**Comment by TheCSharpAcademy** [comment]
@Gautatyr good work! I just had to modify the query to create the DB, yours wasn't working for me and I didn't want to spent too much time investigating 😁😁😁. I had to use this: 
image

**Comment by Gautatyr** [comment]
Thanks !
As for the database it must be because the connection string is inside an App.Config file that I added to the gitignore for protection.

**Pull request merged**
