### PR TITLE
Project finished with extra report challenge

### PR DESCRIPTION
**Pull request by arashi256**

### CODE REVIEW

**Comment by arashi256** [comment]
All errors fixed.

**Review by Doc415 — CHANGES_REQUESTED** [review]
Hey nice UI
when i try do update a flash card i am getting this error
image

**Comment by arashi256** [comment]
All done, ready for re-review.

**Review by Doc415 — APPROVED** [review]
There you go :) 
Nice readme. Makes everything smooth as silk :)

**Pull request closed without merging**
