### PR TITLE
Finished Flashcards Project

### PR DESCRIPTION
**Pull request by N-Endy**
I totally enjoyed this project. Please review and let me know how I can improve.

### CODE REVIEW

**Review by Doc415 — CHANGES_REQUESTED** [review]
Very good work mate. There is only one exception. When i run the program for the first time , and there is no db in my server , when app creating the db, it throws exception.
image

**Comment by N-Endy** [comment]
Thank you @Doc415

I'll look at the code and make the necessary changes. Would the issues from
Codacy prevent my code from being merged?

**Review by Doc415 — CHANGES_REQUESTED** [review]
I am still getting same exception
image

**Comment by Doc415** [comment]
> Thank you @Doc415 I'll look at the code and make the necessary changes. Would the issues from Codacy prevent my code from being merged?


I dont think codacy will be a problem.
You need to check table creation process , it seems like you are referencing a table that is not created yet

**Comment by N-Endy** [comment]
Thanks, @Doc415 I was creating the Flashcards table before Stacks. The
appropriate changes have been made and the code should run without errors
now.

**Review by Doc415 — APPROVED** [review]
Nice work :)

**Pull request closed without merging**
