### PR TITLE
Finished the project

### PR DESCRIPTION
**Pull request by kjanos89**

### CODE REVIEW

**Review by Doc415 — CHANGES_REQUESTED** [review]
Hey there :)
when i press Enter without entering any number in the menu, app throws exception.
image

user may need to see all selectable options and id's when selecting stack or flashcard. We cannot remember id for each option if the list is long. 

image
image
we need to see the id's to check for a requirement

image





image

There is a change stack selection in the menu looks non functional. It can be removed . Each subselection already ask for stack select.

Good luck.

**Comment by kjanos89** [comment]
Hey, @Doc415 ! Thank you for your time on reviewing my code. Very much appreciated!
-So for the first issue I thought the default switch case didn't handle empty strings at first but then I realized its the console.readline() in some options through the different menus that return the user to the main menu, if too many buttons are pressed during the thread.sleep window the menuoption did not have a workaround and simply crashed the app. Its fixed now :)
Changed everything else you asked for.
Once again thank you for your time!

**Review by Doc415 — CHANGES_REQUESTED** [review]
Hey you are fast :) You solved the issues. Yet there is one requirement that does not meet.
The stack and flashcard ids shown to user should be sequental even if you delete a stack.
There should be no gaps.
image

There had been several discussions on the Discord server how to solve this. You can check channels if you have difficulty about tthis requirement.
Good luck.
image

**Comment by kjanos89** [comment]
Oh well I thought that requirement was for flashcards only so I coded it to change the ids on the table, not gonna lie it was difficult.
After some tinkering now I use a dictionary to map the real ids to their index and look them up when the user wants to use them.
Like 2 hours of thinking later that's my best bet how you want to see it working. Passed all my tests, hope its the method you were pointing towards all this time.
Cheers!

**Review by Doc415 — APPROVED** [review]
Nice :) approving now.

**Comment by Doc415** [comment]
Nice work :) Approving now.

**Pull request closed without merging**
