### PR TITLE
Flashcard ready to review

### PR DESCRIPTION
**Pull request by mohammad-premtech**
Please note: I used  PostgreSQL instead of recommended MS SQL because the machine I am working is locked and I can't download MS SQL due to admin rights. Already had PostgreSQL and I'm well versed with SQL queries. Not sure how will you review this, let me know if you have any questions.

### CODE REVIEW

**Comment by Jinboi** [comment]
Hi @mohammad-premtech ,

image


Your project looks great but I can't run the program. Do you konw why? 

Is it becasue of the appsettings?

image

My MSsql is below:

image


Is this because I don't have the database you're using?

image

Or is it because you're using PostgreSQL and I'm using MSSQL?

I'm not sure what's going on. Please advise if you know something. Thank you!

Cheers,
-Youngwoo

**Comment by mohammad-premtech** [comment]
Hi,
I think its because of PostgreSQL as the DbContext files and other packages which are imported will be different. I apologize I couldn't use MS SQL due to my machine being locked and unable to download MS SQL.

I think what could be done is change the database provider to MSSql server and update appsettings.json. I can't actually test this even if I had made changes. Is it possible to download PostgreSQL on your end?

**Comment by Jinboi** [comment]
Hi @mohammad-premtech ,

I'm sorry. I'm kind of stuck.

I've been trying to create a database but it's not working.

I've changed the appsettings to my server/databse like below

{
  "ConnectionStrings": {
    "DefaultConnection": "Data Source=(LocalDB)\\LocalDBDemo;Database=shiftloggerdbForMo;Trusted_Connection=true;TrustServerCertificate=true;"
  }
}

And then I've uninstalled and then installed Npgsql.EntityFrameworkCore.PostgreSQL.

And then I've installed Microsoft.EntityFrameworkCore.Tools. 

And then I went on to PMC and 'Add-Migration Initial-CreateTwo'

But build fails.

I have no idea why. What am I missing?

image

Please advise if you know. 

Once you reply, I'll try again. but if I fail even then, I'll have to ask other reviewers to review this.

Thank you for your patience. 

Cheers,
-Youngwoo

**Comment by Jinboi** [comment]
Hi @mohammad-premtech ,

Sorry to keep you waiting. 

I was able to download pgAdmin and PostgreSQL and connect that to your project.

After I've downloaded ef tools and 'Add-Migration' and 'Update-Database', I was able to create a stack called "Korean" and see it updated in the sever from pgAdmin.

However, I was not able to add flashcards to the stack.

Please see below:

image

image

image

Microsoft.EntityFrameworkCore.DbUpdateException: 'An error occurred while saving the entity changes. See the inner exception for details.'

PostgresException: 42703: column "DisplayOrder" of relation "Flashcards" does not exist

Can you please look into this when you have time?

Please let me know if I'm missing something to run your project correctly.

Hope you have a great weekend!

Thank you and Happy Coding!

Cheers,
-Youngwoo

**Comment by mohammad-premtech** [comment]
Hi @Jinboi 

Thanks for checking out the project! It looks like you're running into an issue with the DisplayOrder column when adding flashcards. I’ve got a few things you can try to get it working:

Make sure you've run the latest migrations:
It appears like the DisplayOrder column hasn’t been added to your database. Running dotnet ef database update should apply all the migrations and get everything synced up.

Please check the __EFMigrationsHistory table:
This table shows which migrations have already been applied. You can query it to make sure everything's up-to-date on your end. Sometimes a migration gets missed, and this will help us spot it.

Also please take a quick look at the Flashcards table schema:
Double-check that the DisplayOrder column exists in the table. Just to confirm the schema is aligned with the current code.
If the above doesn’t work, consider resetting the database:

As a last resort, you could drop the database, recreate it, and run dotnet ef database update again. This should force everything into sync if something went out of order.

Lastly, please check your EF Core and Npgsql versions:
Just make sure you’re using the same versions of these packages as me. Sometimes a version mismatch can cause odd issues during migrations.
Everything is working perfectly on my side, but if it helps, I can attach a video link of the console app running with the database so you can see how it’s working. Let me know if you’d like that!

Let me know if any of this helps! Happy to troubleshoot more if needed.

Thanks,
Mo

**Comment by Jinboi** [comment]
Hi Mo!

https://www.youtube.com/watch?v=gOJ_eEksJjA

Please find attached video.

I've dropped the database and re-created it but still getting the same error.

At this point, I'm at my wits end. I'll talk to Pablo and release this to someone else so that they can review it. 

I have no idea why I'm getting the error.

Thanks for your patience. 

Cheers,
-Youngwoo

**Comment by Jinboi** [comment]
@TheCSharpAcademy ,

Hey Pablo. I'll release this on the tcsa to have someone else to take a look at it. I've been working on this close to a month but can't figure out :(

**Comment by stevietv** [comment]
Hi @mohammad-premtech 
I was able to get your project up and running with a few changes:

* remove the PGSQl package and add the SQLServer package
* Edit the connections that create NpgsqlConnection and NpgsqlCommands to be SqlConnection and SqlCommand
* edit the program to UseSqlServer
* add a correct connection string
* drop all the submitted migrations
* create a solution file for your project - this was needed to allow EFCore to create new migrations (a build config is needed)
* create the migrations and update the DB
* run the project

After that I got it up and running and the project does as it should, so good work here.

There are some caveats though - Normally on this project we haven't yet introduced EFCore yet and want students to write in SQL. As you've said you've got experience there I'm gonna let that slide!
The extended queries for the summaries per year can't be ran as SQLServer doesn't support the EXTRACT command you built in, we're going to have to assume that they work!

Going forward we have a LOT of projects that require SQLServer - Its going to be a pain if our reviewers have to update your programs from PG to SQLServer each time to execute them. Are you able to get an SQLServer somewhere running. It can also be remote that you can connect to!

Approved ✅

**Pull request closed without merging**
