### PR TITLE
Ibrahim Gilani Flashcard application

### PR DESCRIPTION
**Pull request by ibigilani**
finished all requirements but changed the ui menu layout to how i like it

### CODE REVIEW

**Comment by TheCSharpAcademy** [comment]
@ibigilani Just checking if this project is good to go? Asking because you closed it.

**Comment by ibigilani** [comment]
Yea it’s good to goOn Jan 8, 2024, at 12:50 AM, The C# Academy ***@***.***> wrote:﻿
@ibigilani Just checking if this project is good to go? Asking because you closed it.

**Review by TheCSharpAcademy — COMMENTED** [review]
@ibigilani can you update stacks without a problem? I'm getting this:

image. I also got a foreign key conflict error when trying to study a stack.

**Comment by ibigilani** [comment]
Yea both those features worked for me when I tested it last, I’ll test it tomorrow again and create a new pull requestOn Jan 8, 2024, at 1:00 AM, The C# Academy ***@***.***> wrote:﻿
@TheCSharpAcademy commented on this pull request.

@ibigilani can you update stacks without a problem? I'm getting this:
image.png (view on web). I also got a foreign key conflict error when trying to study a stack.

**Comment by TheCSharpAcademy** [comment]
@ibigilani let me know if you need help

**Comment by TheCSharpAcademy** [comment]
@ibigilani closing the PR for admin purposes, but feel free to submit again when you're ready! 🤓

**Pull request closed without merging**
