### PR TITLE
Adding my project

### PR DESCRIPTION
**Pull request by breno085**

### CODE REVIEW

**Review by kimfom01 — CHANGES_REQUESTED** [review]
Hey @breno085 Your files were not pushed to github. Please could you resolve this so that I can review :relaxed:

**Comment by breno085** [comment]
I added now, but i'm having security issues that i don't understand, also the code analysis is saying to remove the unecessary "using System.Configuration;" but i'm actually using it and i tried multiple times to fix the readme style issues but i dont know what is wrong, when i fix the style issue i get another style issue...

**Comment by kimfom01** [comment]
Hey @breno085 I think its okay you can ignore the readme issues. As for the security issue, it seems like you moved the passwords to app.config. I guess that's okay albeit git guardian thinks otherwise :laughing: I will begin the review in a moment

**Comment by breno085** [comment]
Ok, thanks.

**Comment by TheCSharpAcademy** [comment]
@kimfom01 What's the status on this one? 😁

**Comment by kimfom01** [comment]
> @kimfom01 What's the status on this one? 😁

Omg I thought I had dropped the review! :facepalm:

**Review by kimfom01 — CHANGES_REQUESTED** [review]
1. Please change the namespaces to file scoped namespace :smile: 
2. Please clean up commented code in in UserRepository (line 205), and other files :sweat_smile: 
3. If you set a [cascading delete](https://www.sqlshack.com/delete-cascade-and-update-cascade-in-sql-server-foreign-key/) on the stack table, you don't have to delete the flashcards when deleting the stacks. [Learn more about it here](https://www.sqlshack.com/delete-cascade-and-update-cascade-in-sql-server-foreign-key/)


I am so sorry for forgetting about this! :pray:  I thought I had submitted the review!

**Comment by TheCSharpAcademy** [comment]
@kimfom01 It seems like border line approval though, I think we could approve as there isn't anything too serious. Thoughts?

**Comment by kimfom01** [comment]
I guess you are right. 
I just hope my mistake has not discouraged @breno085 from studying 😢

**Review by kimfom01 — APPROVED** [review]

**Pull request closed without merging**
