### PR TITLE
Flashcards project done

### PR DESCRIPTION
**Pull request by ohshie**
Hey, so, a new project from me.
It took me some time to wrap my head around DTO's and why i should even use them. For such a small app it still seems sometimes a bit iffy and "abstraction for the sake of abstraction" but i now see why they can be usefull.
I also should say that using DB via sql commands and not via EF feels like a total ass ngl :D 

anyways, i hope everything is good.

### CODE REVIEW

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@ohshie could you please check into the repository your "appsettings.json"? I believe it's removed by default by gitignore. If that's the case, you can just modify the name of the file or copy and paste its contents into a txt file.

**Comment by ohshie** [comment]
I included it in the latest commit
(excluded because.. i guess i though that it should be private? :D)

**Comment by TheCSharpAcademy** [comment]
> I included it in the latest commit (excluded because.. i guess i though that it should be private? :D)

Yeah always make it private when it has sensitive information. However this is just your local db and it will save me some time 😂😂😂

**Comment by TheCSharpAcademy** [comment]
@ohshie Well done! Great work!

**Pull request merged**
