### PR TITLE
Pushing the Project

### PR DESCRIPTION
**Pull request by javedkhan2k2**

### CODE REVIEW

**Comment by javedkhan2k2** [comment]
I don't know why i can't fix the issue with README.md file. It is very annoying.
To run the Project Please create a Database named Flashcards and export the connection string:
Linus/MacOS: export DB_CONNECTION_STRING="your-connection-string-here"
Windows: $env:DB_CONNECTION_STRING="your-connection-string-here"

**Comment by javedkhan2k2** [comment]
> Hello @javedkhan2k2 ,
> 
> When trying to get report I encountered this error:
> 
> `System.InvalidOperationException: 'Could not find color or style 'marron'.`
> 
> Try to solve it and hit me up when you're done. Good luck!

@BBualdo I fixed the issue. I think i changed the color at the last minute and didn't run it after.
Thanks for pointing it out.

**Comment by BBualdo** [comment]
Really good job on this one.

You forgot to close Markup with [/] (just where you fixed), but I will approve it anyway, just a small mistake 😁

I like the design and UX, you could just use Console.Clear() more often, because menu after some operations is going down in the console. 

And I would take DbContext away from Models folder, it's more than just a Model, it's core class for Database, so it should be in main folder or other verbose folder like Data or something.

Good work, good luck with next projects 😁

**Comment by javedkhan2k2** [comment]
> Really good job on this one.
> 
> You forgot to close Markup with [/] (just where you fixed), but I will approve it anyway, just a small mistake 😁
> 
> I like the design and UX, you could just use Console.Clear() more often, because menu after some operations is going down in the console.
> 
> And I would take DbContext away from Models folder, it's more than just a Model, it's core class for Database, so it should be in main folder or other verbose folder like Data or something.
> 
> Good work, good luck with next projects 😁

Thanks man.
I will follow the instruction in the next projects. I had some difficulties in Project Structure, but now i am learning step by step.

**Pull request closed without merging**
