### PR TITLE
Finished project

### PR DESCRIPTION
**Pull request by Bkohler93**
I didn't complete any of the challenges on this one but am fairly happy with how it turned out.

### CODE REVIEW

**Comment by Bkohler93** [comment]
Codacy had some issues with my sql files and I added what they asked for but now say my syntax is incorrect for the new statements I added (such as `SET NOCOUNT ON`). Hoping I can pass this project with these issues anyways.

**Review by kimfom01 — CHANGES_REQUESTED** [review]
Hello, congratulations on completing this project! 🎊

I encountered a bug while reviewing your project and I'd like you to fix it before I can approve the project 😅

An exception thrown when attempting to update or delete a flashcard
image

**Comment by Bkohler93** [comment]
I fixed that bug. Hope all is good now. Thanks!

**Review by kimfom01 — APPROVED** [review]

**Comment by kimfom01** [comment]
Approved but due to Codacy I can't merge, so I'll just close it

Once more congratulations! :confetti_ball:

**Pull request closed without merging**
