### PR TITLE
done

### PR DESCRIPTION
**Pull request by kwm0304**

### CODE REVIEW

**Comment by kwm0304** [comment]
The 2 codacy issues are for getting my connectionstring

**Review by kimfom01 — CHANGES_REQUESTED** [review]
Hello, congratulations on completing this project! :confetti_ball: 

I encountered a bug while reviewing your project and I'd like you to fix it before I can approve the project :sweat_smile: 

An exception was displayed when trying to change stack name
image

**Comment by kwm0304** [comment]
@kimfom01  Hey thanks for reviewing this. I fixed the problem, should be good now

**Review by kimfom01 — APPROVED** [review]

**Comment by kimfom01** [comment]
> @kimfom01 Hey thanks for reviewing this. I fixed the problem, should be good now

@kwm0304  It seems like Codacy is tripping and is preventing me from merging your code. 

Can you remove the extra `;` at the end of those lines highlighted by Codacy let's see if it will let me merge your code.

**Comment by kwm0304** [comment]
Oh okay, I didn't even notice that the first time. Should be good now

**Pull request merged**
