### PR TITLE
Complete flashcards

### PR DESCRIPTION
**Pull request by wkktoria**
It was the most difficult project so far on my programming learning path. I guess some stuff could be done better, but I am glad, that I managed to finish it. 😅

### CODE REVIEW

**Comment by wkktoria** [comment]
Code Analysis wants remove something that cannot be removed.

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@wkktoria Thanks for submitting, looking good! I couldn't find an option to study the cards?
image

image

**Comment by wkktoria** [comment]
An option to study stacks is available in main menu. ☺️ 

flashcards-main-menu


flashcards-study-stacks

flashcards-study-session

**Comment by wkktoria** [comment]
I have added this option also to stack menu. 😄

**Comment by wkktoria** [comment]
> @wkktoria Thanks for submitting, looking good! I couldn't find an option to study the cards? image
> 
> image

That option is available in main menu, but I added it also to stack menu as explained above.

**Comment by TheCSharpAcademy** [comment]
@wkktoria Sorry I must have been blind 😒

**Pull request merged**
