### PR TITLE
Submission Flashcards project

### PR DESCRIPTION
**Pull request by antonderegt**
Hi, 

Please let me know what you think! ;)

### CODE REVIEW

**Comment by Doc415** [comment]
Hey there It seems you have sent your project as a submodule. Could you please sent it again? We cant see the files when it is a submodule. You need to remove git files and folders from the original directory before you commit and push.

**Review by Doc415 — CHANGES_REQUESTED** [review]
Submitted as a submodule.

**Comment by antonderegt** [comment]
Sorry @Doc415. I was so happy Codacy didn't fail 🤣 . Next time I'll check if the files are visible. 

It's saying 13 files changed now!

**Review by Doc415 — CHANGES_REQUESTED** [review]
hey there i was exited about seeing Codacy tests was all green 😄 
We have some small issues to fix here.

1-When i try to add flashcard before i add any stack , i stuck :) cant go back to main menu
image

2-When i try to see the study report i am getting this exception
image

Suggestion:
image

The "Quit" selection under managing stacks and flascards feels like it is going to quit the application. I would prefer something like "Return to main menu"

**Comment by antonderegt** [comment]
Hi @Doc415 thanks for the review! 
I solved issue 1 by checking if there are no stacks, if there are no stacks it will ask you to create one first.

Issue 2 I wasn’t able to reproduce. Judging by the error message it might have something to do with how I referenced the table: `[Flashcards].[dbo].[StudySessions]`, I changed it to just: `StudySessions`. I hope this fixes the error. If not maybe you can show me what you have in your database, if it’s not too much to ask.

Thanks for your suggestion about the menu, definitely makes it more clear!

You right about the cascade delete, it shouldn’t cascade delete when deleting a study session. I removed that part.

Thanks again for the review! I learned to put more focus on error handling.

**Review by Doc415 — APPROVED** [review]
Thanks for your collaboration.
Approving your project.

**Comment by antonderegt** [comment]
You're fast thanks @Doc415

**Pull request closed without merging**
