### PR TITLE
Completed Project

### PR DESCRIPTION
**Pull request by PokingOutsideOFF**
Fun Project..!!

### CODE REVIEW

**Comment by Jinboi** [comment]
Hi @PokingOutsideOFF ,

Thank you for submitting your project.

Your project looks great! But there's a minor mistake that needs to be fixed.

I was able to create two Stacks called "Korean" when they should have unique names.

Please look into this when you have time! Thank you! 

image

Cheers,
-Youngwoo

**Comment by Jinboi** [comment]
Thank you for submitting your project. I'll get back to you shortly. Thank you!

**Comment by PokingOutsideOFF** [comment]
While adding entry of same name I catch this error as I have declared a unique constraint on StackName in the Stack Model
image

**Comment by Jinboi** [comment]
Hi @PokingOutsideOFF ,

Sorry—my wires got mixed up and I was looking at someone else's project when writing previous comments. 

Anyways—yes, nothing's wrong with your project and your project looks great!

I'll mark it as completed and please move on to the next project!

Cheers! 
-Youngwoo 

P.S
Just out of curiosity—why are you using version 6.0.33 for your project instead of the latest version?

**Pull request closed without merging**
