### PR TITLE
Finished project

### PR DESCRIPTION
**Pull request by JsPeanut**
Hello there! I would like to ask to whoever is correcting this, if you could tell me how I could refactor my code or give me some tips, because I feel my code is way too long and it could be simplified. Thanks in advance!

### CODE REVIEW

**Comment by TheCSharpAcademy** [comment]
@JsPeanut Hi there! Could you please submit this project in the academy's dashboard? 😊

**Comment by TheCSharpAcademy** [comment]
> Hello there! I would like to ask to whoever is correcting this, if you could tell me how I could refactor my code or give me some tips, because I feel my code is way too long and it could be simplified. Thanks in advance!

@JsPeanut No worries, I'll see if your code is too verbose and will let you know 😊

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@JsPeanut I don't think your code is verbose. This is a complex project, so it demands lots of lines. 

For better readability of SQL queries I do recommend you put one property on each line, it's just easier to maintain. Example: 

image

Also I've just noticed you have a "stack name" property in your study sessions. That defeats the purpose of relational data since you're essentially duplicating data (as there's already a name property in your stack table). Ideally you want to JOIN your table with the stack table to grab the name of the stack.

**Comment by JsPeanut** [comment]
> @JsPeanut I don't think your code is verbose. This is a complex project, so it demands lots of lines.
> 
> For better readability of SQL queries I do recommend you put one property on each line, it's just easier to maintain. Example:
> 
> image
> 
> Also I've just noticed you have a "stack name" property in your study sessions. That defeats the purpose of relational data since you're essentially duplicating data (as there's already a name property in your stack table). Ideally you want to JOIN your table with the stack table to grab the name of the stack.

Thank you man. Will fix later what you told me to on this project and on the other one because it's a bit late here!

**Comment by TheCSharpAcademy** [comment]
@JsPeanut Let me know if you need help! This is the only project that's standing between you and the yellow belt. With that upgrade you'll be able to review other student's code 😁

**Comment by JsPeanut** [comment]
> @JsPeanut Let me know if you need help! This is the only project that's standing between you and the yellow belt. With that upgrade you'll be able to review other student's code 😁

Thanks! I'll tell you.

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@JsPeanut Hey! I tried to update a flashcard and it didn't work. Not sure what happened. 

Also I'm being a pain but I think you forgot the closing square bracket 😁
image

**Comment by JsPeanut** [comment]
> @JsPeanut Hey! I tried to update a flashcard and it didn't work. Not sure what happened.
> 
> Also I'm being a pain but I think you forgot the closing square bracket 😁 image

Will fix it later, thank you for telling me

**Comment by TheCSharpAcademy** [comment]
@JsPeanut Let me know if you need help 😊

**Comment by JsPeanut** [comment]
Fixed the update issue. Regarding the closing square bracket, couldn't find a fix for that, sorry. Got the menu from a YT video

**Comment by JsPeanut** [comment]
> Fixed the update issue. Regarding the closing square bracket, couldn't find a fix for that, sorry. Got the menu from a YT video

If I even try to edit the variable _decorator_, my menu options will break

**Review by TheCSharpAcademy — CHANGES_REQUESTED** [review]
@JsPeanut Well done, that's fixed now. You're close!

Looks like there's something wrong retrieving the study sessions though, could you please check? it happens when I try to see the sessions, or the average.

image

**Comment by JsPeanut** [comment]
> @JsPeanut Well done, that's fixed now. You're close!
> 
> Looks like there's something wrong retrieving the study sessions though, could you please check? it happens when I try to see the sessions, or the average.
> 
> image

Fixed it!

**Comment by TheCSharpAcademy** [comment]
@JsPeanut Congrats on getting your yellow belt! I can't remember your discord nickname, could you please update it on the platform (if you want to)?

**Pull request merged**
